-- H.5: Generator.generateAccountNumber() used an in-memory static counter that reset to 0
-- on every JVM restart, colliding with account_number/iban values already persisted from
-- before the restart. A DB sequence survives restarts and is safe across multiple instances.
-- Started at 1000 (not 1) to stay clear of low account_number values already generated by
-- the old in-memory counter before this migration.
CREATE SEQUENCE account_number_seq START WITH 1000;
